# Generated by Django 6.0.7 on 2026-07-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfig_provider_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent campaign if this is a sub-campaign (e.g. outreach 1)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_campaigns', to='core.campaign'),
        ),
    ]
