# Generated by Django 6.0.7 on 2026-07-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campaign_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='action_fraction',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_freemium',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='model_blob',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='parent',
        ),
    ]
