# Generated by Django 6.0.7 on 2026-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_campaign_action_fraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='override_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='simulated_task',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
