# Generated by Django 6.0.7 on 2026-07-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfig_override_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('email', 'Email'), ('reply_unread', 'Reply Unread'), ('first_message', 'First Message'), ('extract_leads', 'Extract Leads')], max_length=20),
        ),
    ]
