# Generated by Django 6.1 on 2026-08-15 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50, unique=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('fallback_invocations', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Health',
                'verbose_name_plural': 'Provider Healths',
            },
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('execution_mode', models.CharField(default='manual', max_length=50)),
                ('workflows_executed', models.JSONField(blank=True, default=list)),
                ('workflows_disabled', models.JSONField(blank=True, default=list)),
                ('workflows_skipped', models.JSONField(blank=True, default=list)),
                ('actions_completed', models.IntegerField(default=0)),
                ('deal_errors', models.IntegerField(default=0)),
                ('workflow_errors', models.IntegerField(default=0)),
                ('fatal_errors', models.IntegerField(default=0)),
                ('browser_recoveries', models.IntegerField(default=0)),
                ('llm_deferrals', models.IntegerField(default=0)),
                ('diagnostics_generated', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Session History',
                'verbose_name_plural': 'Session Histories',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='last_config_save',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_provider', models.CharField(default='', max_length=50)),
                ('fallback_provider', models.CharField(default='', max_length=50)),
                ('primary_calls', models.IntegerField(default=0)),
                ('fallback_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('structured_output_calls', models.IntegerField(default=0)),
                ('retries', models.IntegerField(default=0)),
                ('estimated_input_tokens', models.IntegerField(default=0)),
                ('estimated_output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='core.sessionhistory')),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
            },
        ),
    ]
