# Generated by Django 6.0.7 on 2026-07-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0011_linkedinprofile_contribute_to_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='contribute_to_hub',
        ),
    ]
