# Generated by Django 6.0.7 on 2026-07-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0012_remove_linkedinprofile_contribute_to_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='newsletter_processed',
        ),
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='subscribe_newsletter',
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='connect_weekly_limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
