# Generated by Django 6.0.7 on 2026-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_remove_linkedinprofile_newsletter_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='profiles_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='profiles_qualified',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
