# Generated by Django 6.1 on 2026-08-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0014_searchkeyword_is_deprecated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('reply', 'Reply')], max_length=20),
        ),
    ]
