# Generated by Django 6.0.7 on 2026-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_lead_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='llm_is_qualified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='llm_qualification_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='llm_qualification_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
