# Generated by Django 6.0.7 on 2026-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_lead_llm_is_qualified_lead_llm_qualification_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('Ready to Email', 'Ready To Email'), ('Emailed', 'Emailed'), ('Ready to Connect', 'Ready To Connect'), ('Pending', 'Pending'), ('Connected', 'Connected'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Lead', 'Lead'), ('Responded', 'Responded'), ('Nurturing', 'Nurturing'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Qualified', max_length=20),
        ),
    ]
