# Generated by Django 6.0.7 on 2026-07-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_deal_state'),
        ('linkedin', '0014_searchkeyword_is_deprecated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_leads', to='linkedin.searchkeyword'),
        ),
    ]
