# Generated by Django 6.0.7 on 2026-07-27 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfig_override_expires_at_and_more'),
        ('crm', '0018_add_lead_source_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('connect_requested', 'Connection Requested'), ('connect_accepted', 'Connection Accepted'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received'), ('email_sent', 'Email Sent')], max_length=50, verbose_name='Event Type')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='core.campaign', verbose_name='Campaign')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='crm.deal', verbose_name='Deal')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
