# Generated by Django 6.0.7 on 2026-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_add_event_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='last_withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='withdraw_count',
            field=models.IntegerField(default=0),
        ),
    ]
