# Generated by Django 6.0.7 on 2026-07-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_add_deal_withdrawal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='first_message_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
