# Generated by Django 6.0.7 on 2026-07-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_deal_first_message_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='connection_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
