# Generated by Django 6.0.7 on 2026-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_deal_connection_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='next_action_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
